### ISSUE TITLE
Add value to the app

### ISSUE THREAD

**Issue by itsmanojb** [shubhambattoo/progressive-weather-app#1]
* **I'm submitting a ...**
  - [x] bug report
  - [x] feature request
  - [ ] support request

* **Do you want to request a *feature* or report a *bug*?**
Both.

* **What is the current behavior?**

1. Only weather of searched city is shown.
2. When no place found after search, nothing happens.

* **If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem** 
Check out the SS taken after search failed.

![image](https://user-images.githubusercontent.com/11155266/94576899-82a17700-0293-11eb-95fc-4a4132bf4e84.png)

* **What is the expected behavior?**
1. By default it should show weather of current location.
2. If no results found, it should show message saying so.

* **What is the motivation / use case for changing the behavior?**
This basic application can be little bit more useful, if user is presented with data w/o any additional input at start up.

**Comment by shubhambattoo** [comment]
Do you want to take this up?
